import { formatJalali, toPersianDigits } from "@/lib/jalali";

// Dynamically imported inside exportPedigreePdf() — both are export-only,
// browser-only libraries with no reason to load until the user actually
// asks for a PDF (and no reason to risk touching `window` during the
// static-export build's prerender pass at all).

export type PdfPageSize = "a4-portrait" | "a3-landscape";

const PAGE_MM: Record<PdfPageSize, { w: number; h: number; format: "a4" | "a3"; orientation: "portrait" | "landscape" }> = {
  "a4-portrait": { w: 210, h: 297, format: "a4", orientation: "portrait" },
  "a3-landscape": { w: 420, h: 297, format: "a3", orientation: "landscape" },
};

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch("/brand/logo-full.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function waitForImage(img: HTMLImageElement): Promise<void> {
  return new Promise((resolve) => {
    if (img.complete) {
      resolve();
      return;
    }
    img.onload = () => resolve();
    img.onerror = () => resolve();
  });
}

export function downloadDataUrl(dataUrl: string, filename: string) {
  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = filename;
  a.click();
}

/**
 * Builds a print-quality PDF from an already-rasterized tree PNG. jsPDF's
 * built-in text() has no Arabic/Persian shaping or bidi support, so instead
 * of drawing header/footer text natively, this composes a full off-screen
 * "printable page" (header with logo + title, the tree image, footer) as
 * real DOM and rasterizes THAT as one image — every glyph goes through the
 * browser's own font rendering, exactly like the on-screen UI, then jsPDF
 * just wraps that single image in a correctly-sized PDF page.
 */
export async function exportPedigreePdf(
  treeDataUrl: string,
  info: { animalLabel: string; generationCount: number; pageSize: PdfPageSize }
): Promise<void> {
  const logoDataUrl = await loadLogoDataUrl();
  const dateLabel = formatJalali(new Date().toISOString().slice(0, 10), true);

  const page = document.createElement("div");
  page.dir = "rtl";
  Object.assign(page.style, {
    position: "fixed",
    left: "-99999px",
    top: "0",
    width: "1400px",
    background: "#ffffff",
    padding: "40px",
    fontFamily: getComputedStyle(document.body).fontFamily || "sans-serif",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  } as CSSStyleDeclaration);

  page.innerHTML = `
    <div style="display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #2E7D32; padding-bottom:20px;">
      <div style="display:flex; align-items:center; gap:14px;">
        ${logoDataUrl ? `<img src="${logoDataUrl}" style="width:64px;height:64px;object-fit:contain;" />` : ""}
        <div>
          <div style="font-size:26px; font-weight:700; color:#1B5E20;">گله‌یار</div>
          <div style="font-size:15px; color:#555;">دستیار هوشمند مدیریت دامداری</div>
        </div>
      </div>
      <div style="text-align:left; font-size:14px; color:#555; line-height:1.9;">
        <div>شجره‌نامه: ${info.animalLabel}</div>
        <div>تعداد نسل نمایش‌داده‌شده: ${toPersianDigits(info.generationCount)}</div>
        <div>تاریخ خروجی: ${dateLabel}</div>
      </div>
    </div>
    <div id="pdf-tree-slot" style="display:flex; justify-content:center;"></div>
    <div style="border-top:1px solid #ddd; padding-top:10px; text-align:center; font-size:12px; color:#888;">
      Generated by Galeyar
    </div>
  `;
  document.body.appendChild(page);

  try {
    const treeImg = document.createElement("img");
    treeImg.src = treeDataUrl;
    treeImg.style.maxWidth = "100%";
    page.querySelector("#pdf-tree-slot")!.appendChild(treeImg);
    await waitForImage(treeImg);

    const { toPng } = await import("html-to-image");
    const fullPageDataUrl = await toPng(page, { pixelRatio: 2, backgroundColor: "#ffffff" });

    const fullImg = new Image();
    fullImg.src = fullPageDataUrl;
    await waitForImage(fullImg);

    const { w, h, format, orientation } = PAGE_MM[info.pageSize];
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation, unit: "mm", format });

    const imgRatio = fullImg.width / fullImg.height || 1;
    const pageRatio = w / h;
    let renderW = w;
    let renderH = h;
    if (imgRatio > pageRatio) {
      renderH = w / imgRatio;
    } else {
      renderW = h * imgRatio;
    }
    const offsetX = (w - renderW) / 2;
    const offsetY = (h - renderH) / 2;

    doc.addImage(fullPageDataUrl, "PNG", offsetX, offsetY, renderW, renderH);
    doc.save(`shajarename-${info.animalLabel}.pdf`);
  } finally {
    document.body.removeChild(page);
  }
}
