import { formatJalali } from "@/lib/jalali";

function waitForImage(img: HTMLImageElement): Promise<void> {
  return new Promise((resolve) => {
    if (img.complete) {
      resolve();
      return;
    }
    img.onload = () => resolve();
    img.onerror = () => resolve();
  });
}

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch("/brand/logo-full.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

/**
 * Generic branded-PDF export for any report table: rasterizes the given DOM
 * node (a plain table/list, not a pannable canvas, so no viewport-fitting
 * trick is needed like the pedigree graph export), composes it below a
 * logo/title header and a footer, and rasterizes *that* — same reasoning as
 * src/lib/pdf-export.ts: jsPDF's text() has no Persian shaping, so every
 * glyph goes through the real browser font instead.
 */
export async function exportReportPdf(container: HTMLElement, reportTitle: string): Promise<void> {
  const { toPng } = await import("html-to-image");
  const contentDataUrl = await toPng(container, { pixelRatio: 2, backgroundColor: "#ffffff" });
  const logoDataUrl = await loadLogoDataUrl();
  const dateLabel = formatJalali(new Date().toISOString().slice(0, 10), true);

  const page = document.createElement("div");
  page.dir = "rtl";
  Object.assign(page.style, {
    position: "fixed",
    left: "-99999px",
    top: "0",
    width: "1000px",
    background: "#ffffff",
    padding: "32px",
    fontFamily: getComputedStyle(document.body).fontFamily || "sans-serif",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  } as CSSStyleDeclaration);

  page.innerHTML = `
    <div style="display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #2E7D32; padding-bottom:16px;">
      <div style="display:flex; align-items:center; gap:12px;">
        ${logoDataUrl ? `<img src="${logoDataUrl}" style="width:56px;height:56px;object-fit:contain;" />` : ""}
        <div>
          <div style="font-size:22px; font-weight:700; color:#1B5E20;">گله‌یار</div>
          <div style="font-size:13px; color:#555;">دستیار هوشمند مدیریت دامداری</div>
        </div>
      </div>
      <div style="text-align:left; font-size:13px; color:#555;">
        <div>${reportTitle}</div>
        <div>تاریخ: ${dateLabel}</div>
      </div>
    </div>
    <div id="report-content-slot" style="display:flex; justify-content:center;"></div>
    <div style="border-top:1px solid #ddd; padding-top:8px; text-align:center; font-size:11px; color:#888;">
      Generated by Galeyar
    </div>
  `;
  document.body.appendChild(page);

  try {
    const img = document.createElement("img");
    img.src = contentDataUrl;
    img.style.maxWidth = "100%";
    page.querySelector("#report-content-slot")!.appendChild(img);
    await waitForImage(img);

    const fullPageDataUrl = await toPng(page, { pixelRatio: 2, backgroundColor: "#ffffff" });
    const fullImg = new Image();
    fullImg.src = fullPageDataUrl;
    await waitForImage(fullImg);

    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageW = 210;
    const pageH = 297;
    const imgRatio = fullImg.width / fullImg.height || 1;
    const pageRatio = pageW / pageH;
    let renderW = pageW;
    let renderH = pageH;
    if (imgRatio > pageRatio) renderH = pageW / imgRatio;
    else renderW = pageH * imgRatio;
    const offsetX = (pageW - renderW) / 2;
    const offsetY = (pageH - renderH) / 2;
    doc.addImage(fullPageDataUrl, "PNG", offsetX, offsetY, renderW, renderH);
    doc.save(`${reportTitle}.pdf`);
  } finally {
    document.body.removeChild(page);
  }
}
